name: chattah
description: A fast app to chat with all your friends
version: 1.0.2+2

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^4.12.1
  firebase_auth: ^6.5.6
  cloud_firestore: ^6.7.1
  provider: ^6.0.1
  google_sign_in: ^7.2.0
  font_awesome_flutter: ^11.0.0
  local_auth: ^3.0.2
  flutter_local_notifications: ^22.1.0
  swipe_to: ^1.0.2
  visibility_detector: ^0.4.0+2
  file_picker: ^11.0.2
  firebase_storage: ^13.4.5
  timezone: ^0.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
